---
all:
  children:
    pcs_servers:
       hosts:
         node01:
           ansible_host: "192.168.56.3"
           ansible_private_key_file: ".vagrant/machines/node01/virtualbox/private_key"
         node02:
           ansible_host: "192.168.56.4"
           ansible_private_key_file: ".vagrant/machines/node02/virtualbox/private_key"
         node03:
           ansible_host: "192.168.56.5"
           ansible_private_key_file: ".vagrant/machines/node03/virtualbox/private_key"
       vars:
         virtualbox_host: "192.168.56.1"
         virtualbox_host_username: "alexey"
         virtualbox_host_password: "strong_pass"
  vars:
    domain: "mydomain.test"
    ntp_timezone: "Europe/Moscow"
    pcs_password: "strong_pass" # cluster user: hacluster
    cluster_name: "hacluster"
...