---
all:
  children:
    pcs_servers:
       hosts:
         node01:
           ansible_host: "192.168.56.101"
           #ansible_port: "2220"
           ansible_private_key_file: "../.vagrant/machines/node01/virtualbox/private_key"
         node02:
           ansible_host: "192.168.56.102"
           #ansible_port: "2221"
           ansible_private_key_file: "../.vagrant/machines/node02/virtualbox/private_key"
         node03:
           ansible_host: "192.168.56.103"
           #ansible_port: "2222"
           ansible_private_key_file: "../.vagrant/machines/node03/virtualbox/private_key"
       vars:
         virtualbox_host: "192.168.56.1"
         virtualbox_host_username: "alexey"
         virtualbox_host_password: "labpas"
  vars:
    domain: "mydomain.test"
    ntp_timezone: Europe/Moscow
    pcs_password: "labpas" # cluster user: hacluster
    cluster_name: "hacluster"
...